//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BajasHotel
    {
        public int baj_id { get; set; }
        public int baj_hot_id { get; set; }
        public System.DateTime baj_fecha_inicio { get; set; }
        public System.DateTime baj_fecha_fin { get; set; }
        public string baj_motivo { get; set; }
    
        public virtual Hoteles Hoteles { get; set; }
    }
}
