//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes_Estadias
    {
        public Nullable<long> cye_cli_documento { get; set; }
        public int cye_est_res_id { get; set; }
        public int cye_hab_id { get; set; }
        public int cye_hab_hot_id { get; set; }
        public Nullable<int> cye_cli_doc_id { get; set; }
        public Nullable<int> cye_cye_id { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Estadias Estadias { get; set; }
        public virtual Habitaciones Habitaciones { get; set; }
    }
}
