//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesErrores
    {
        public ClientesErrores()
        {
            this.Facturas = new HashSet<Facturas>();
            this.Reservas = new HashSet<Reservas>();
        }
    
        public int cye_doc_id { get; set; }
        public long cye_documento { get; set; }
        public string cye_nombre { get; set; }
        public string cye_apellido { get; set; }
        public string cye_mail { get; set; }
        public string cye_nacionalidad { get; set; }
        public System.DateTime cye_fecha_nach { get; set; }
        public Nullable<bool> cye_habilitado { get; set; }
        public string cye_calle { get; set; }
        public Nullable<int> cye_calle_nro { get; set; }
        public string cye_piso { get; set; }
        public string cye_depto { get; set; }
        public string cye_dir_localidad { get; set; }
        public string cye_dir_pais { get; set; }
        public string cye_telefono { get; set; }
        public string cye_error { get; set; }
        public int cye_id { get; set; }
    
        public virtual Documentos Documentos { get; set; }
        public virtual ICollection<Facturas> Facturas { get; set; }
        public virtual ICollection<Reservas> Reservas { get; set; }
    }
}
