//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public Clientes()
        {
            this.Clientes_Estadias = new HashSet<Clientes_Estadias>();
            this.Facturas = new HashSet<Facturas>();
            this.Reservas = new HashSet<Reservas>();
        }
    
        public long cli_documento { get; set; }
        public int cli_doc_id { get; set; }
        public string cli_nombre { get; set; }
        public string cli_apellido { get; set; }
        public string cli_mail { get; set; }
        public string cli_nacionalidad { get; set; }
        public System.DateTime cli_fecha_nac { get; set; }
        public bool cli_habilitado { get; set; }
        public string cli_calle { get; set; }
        public Nullable<int> cli_calle_nro { get; set; }
        public string cli_piso { get; set; }
        public string cli_depto { get; set; }
        public string cli_dir_localidad { get; set; }
        public string cli_dir_pais { get; set; }
        public string cli_telefono { get; set; }
    
        public virtual Documentos Documentos { get; set; }
        public virtual ICollection<Clientes_Estadias> Clientes_Estadias { get; set; }
        public virtual ICollection<Facturas> Facturas { get; set; }
        public virtual ICollection<Reservas> Reservas { get; set; }
    }
}
