//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumibles
    {
        public Consumibles()
        {
            this.Items_Facturas = new HashSet<Items_Facturas>();
        }
    
        public int con_id { get; set; }
        public string con_desc { get; set; }
        public int con_precio { get; set; }
    
        public virtual ICollection<Items_Facturas> Items_Facturas { get; set; }
    }
}
