//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentos
    {
        public Documentos()
        {
            this.Clientes = new HashSet<Clientes>();
            this.ClientesErrores = new HashSet<ClientesErrores>();
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int doc_id { get; set; }
        public string doc_desc { get; set; }
    
        public virtual ICollection<Clientes> Clientes { get; set; }
        public virtual ICollection<ClientesErrores> ClientesErrores { get; set; }
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
