//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estados
    {
        public Estados()
        {
            this.Reservas = new HashSet<Reservas>();
        }
    
        public int estados_id { get; set; }
        public string estados_desc { get; set; }
    
        public virtual ICollection<Reservas> Reservas { get; set; }
    }
}
