//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estadias
    {
        public Estadias()
        {
            this.Clientes_Estadias = new HashSet<Clientes_Estadias>();
            this.Facturas = new HashSet<Facturas>();
            this.Items_Facturas = new HashSet<Items_Facturas>();
        }
    
        public int est_res_id { get; set; }
        public int est_usu_alta { get; set; }
        public Nullable<System.DateTime> est_checkin { get; set; }
        public Nullable<System.DateTime> est_checkout { get; set; }
        public Nullable<int> est_cant_noches { get; set; }
        public int est_precio { get; set; }
        public Nullable<int> est_usu_salida { get; set; }
        public Nullable<int> est_dias_sobrantes { get; set; }
    
        public virtual ICollection<Clientes_Estadias> Clientes_Estadias { get; set; }
        public virtual Reservas Reservas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
        public virtual ICollection<Facturas> Facturas { get; set; }
        public virtual ICollection<Items_Facturas> Items_Facturas { get; set; }
    }
}
