//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public Facturas()
        {
            this.Items_Facturas = new HashSet<Items_Facturas>();
        }
    
        public int fac_id { get; set; }
        public Nullable<long> fac_cli_documento { get; set; }
        public System.DateTime fac_fecha { get; set; }
        public int fac_total { get; set; }
        public int fac_est_res_id { get; set; }
        public int fac_med_id { get; set; }
        public Nullable<int> fac_tar_id { get; set; }
        public Nullable<int> fac_cli_doc_id { get; set; }
        public Nullable<int> fac_cye_id { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual ClientesErrores ClientesErrores { get; set; }
        public virtual Estadias Estadias { get; set; }
        public virtual MediosPago MediosPago { get; set; }
        public virtual Tarjetas Tarjetas { get; set; }
        public virtual ICollection<Items_Facturas> Items_Facturas { get; set; }
    }
}
