//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionalidades
    {
        public Funcionalidades()
        {
            this.Roles = new HashSet<Roles>();
        }
    
        public int fun_id { get; set; }
        public string fun_desc { get; set; }
    
        public virtual ICollection<Roles> Roles { get; set; }
    }
}
