//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitaciones
    {
        public Habitaciones()
        {
            this.Clientes_Estadias = new HashSet<Clientes_Estadias>();
            this.Reservas = new HashSet<Reservas>();
        }
    
        public int hab_id { get; set; }
        public int hab_hot_id { get; set; }
        public int hab_tip_id { get; set; }
        public int hab_numero { get; set; }
        public int hab_piso { get; set; }
        public string hab_vista { get; set; }
        public string hab_desc { get; set; }
        public Nullable<bool> hab_habilitado { get; set; }
        public Nullable<int> hab_tipo_porcentual { get; set; }
    
        public virtual ICollection<Clientes_Estadias> Clientes_Estadias { get; set; }
        public virtual Hoteles Hoteles { get; set; }
        public virtual TiposHabitaciones TiposHabitaciones { get; set; }
        public virtual ICollection<Reservas> Reservas { get; set; }
    }
}
