//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoteles_Usuarios
    {
        public int hyu_usu_id { get; set; }
        public int hyu_hot_id { get; set; }
        public int hyu_id { get; set; }
    
        public virtual Hoteles Hoteles { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
