//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoteles
    {
        public Hoteles()
        {
            this.BajasHotel = new HashSet<BajasHotel>();
            this.Habitaciones = new HashSet<Habitaciones>();
            this.Hoteles_Usuarios = new HashSet<Hoteles_Usuarios>();
            this.Regimenes_Hoteles = new HashSet<Regimenes_Hoteles>();
        }
    
        public int hot_id { get; set; }
        public string hot_nombre { get; set; }
        public Nullable<int> hot_estrellas { get; set; }
        public string hot_calle { get; set; }
        public Nullable<int> hot_calle_nro { get; set; }
        public string hot_ciudad { get; set; }
        public string hot_pais { get; set; }
        public string hot_mail { get; set; }
        public string hot_telefono { get; set; }
        public Nullable<System.DateTime> hot_fecha_cre { get; set; }
        public Nullable<bool> hot_habilitado { get; set; }
        public Nullable<int> hot_recarga_estrellas { get; set; }
    
        public virtual ICollection<BajasHotel> BajasHotel { get; set; }
        public virtual ICollection<Habitaciones> Habitaciones { get; set; }
        public virtual ICollection<Hoteles_Usuarios> Hoteles_Usuarios { get; set; }
        public virtual ICollection<Regimenes_Hoteles> Regimenes_Hoteles { get; set; }
    }
}
