//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items_Facturas
    {
        public int iyf_id { get; set; }
        public Nullable<int> iyf_con_id { get; set; }
        public Nullable<int> iyf_fac_id { get; set; }
        public Nullable<int> iyf_cantidad { get; set; }
        public Nullable<int> iyf_monto { get; set; }
        public int iyf_est_res_id { get; set; }
    
        public virtual Consumibles Consumibles { get; set; }
        public virtual Estadias Estadias { get; set; }
        public virtual Facturas Facturas { get; set; }
    }
}
