//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediosPago
    {
        public MediosPago()
        {
            this.Facturas = new HashSet<Facturas>();
        }
    
        public int med_id { get; set; }
        public string med_desc { get; set; }
    
        public virtual ICollection<Facturas> Facturas { get; set; }
    }
}
