//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regimenes
    {
        public Regimenes()
        {
            this.Regimenes_Hoteles = new HashSet<Regimenes_Hoteles>();
            this.Reservas = new HashSet<Reservas>();
        }
    
        public int reg_id { get; set; }
        public string reg_desc { get; set; }
        public int reg_precio { get; set; }
        public Nullable<bool> reg_habilitado { get; set; }
    
        public virtual ICollection<Regimenes_Hoteles> Regimenes_Hoteles { get; set; }
        public virtual ICollection<Reservas> Reservas { get; set; }
    }
}
