//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regimenes_Hoteles
    {
        public int ryh_hot_id { get; set; }
        public int ryh_reg_id { get; set; }
        public int ryh_id { get; set; }
    
        public virtual Hoteles Hoteles { get; set; }
        public virtual Regimenes Regimenes { get; set; }
    }
}
