//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        public Reservas()
        {
            this.Usuarios_ReservasModificaciones = new HashSet<Usuarios_ReservasModificaciones>();
            this.Usuarios_ReservasCancelaciones = new HashSet<Usuarios_ReservasCancelaciones>();
            this.Habitaciones = new HashSet<Habitaciones>();
        }
    
        public int res_id { get; set; }
        public int res_estados_id { get; set; }
        public System.DateTime res_fecha { get; set; }
        public System.DateTime res_inicio { get; set; }
        public System.DateTime res_fin { get; set; }
        public int res_tip_id { get; set; }
        public int res_reg_id { get; set; }
        public Nullable<long> res_cli_documento { get; set; }
        public int res_usu_id { get; set; }
        public Nullable<int> res_cli_doc_id { get; set; }
        public Nullable<int> res_cye_id { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual ClientesErrores ClientesErrores { get; set; }
        public virtual Estadias Estadias { get; set; }
        public virtual Estados Estados { get; set; }
        public virtual Regimenes Regimenes { get; set; }
        public virtual TiposHabitaciones TiposHabitaciones { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual ICollection<Usuarios_ReservasModificaciones> Usuarios_ReservasModificaciones { get; set; }
        public virtual ICollection<Usuarios_ReservasCancelaciones> Usuarios_ReservasCancelaciones { get; set; }
        public virtual ICollection<Habitaciones> Habitaciones { get; set; }
    }
}
