//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.Funcionalidades = new HashSet<Funcionalidades>();
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int rol_id { get; set; }
        public string rol_nombre { get; set; }
        public bool rol_estado { get; set; }
    
        public virtual ICollection<Funcionalidades> Funcionalidades { get; set; }
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
