//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjetas
    {
        public Tarjetas()
        {
            this.Facturas = new HashSet<Facturas>();
        }
    
        public int tar_id { get; set; }
        public string tar_emisor { get; set; }
        public string tar_banco { get; set; }
        public long tar_numero { get; set; }
        public string tar_titular { get; set; }
    
        public virtual ICollection<Facturas> Facturas { get; set; }
    }
}
