//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposHabitaciones
    {
        public TiposHabitaciones()
        {
            this.Habitaciones = new HashSet<Habitaciones>();
            this.Reservas = new HashSet<Reservas>();
        }
    
        public int tip_id { get; set; }
        public string tip_nombre { get; set; }
        public int tip_porcentual { get; set; }
        public int tip_personas { get; set; }
    
        public virtual ICollection<Habitaciones> Habitaciones { get; set; }
        public virtual ICollection<Reservas> Reservas { get; set; }
    }
}
