//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios_ReservasModificaciones
    {
        public int urm_id { get; set; }
        public int urm_res_id { get; set; }
        public int urm_usu_id { get; set; }
        public System.DateTime urm_fecha { get; set; }
    
        public virtual Reservas Reservas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
