//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Estadias = new HashSet<Estadias>();
            this.Estadias1 = new HashSet<Estadias>();
            this.Hoteles_Usuarios = new HashSet<Hoteles_Usuarios>();
            this.Reservas = new HashSet<Reservas>();
            this.Usuarios_ReservasCancelaciones = new HashSet<Usuarios_ReservasCancelaciones>();
            this.Usuarios_ReservasModificaciones = new HashSet<Usuarios_ReservasModificaciones>();
            this.Roles = new HashSet<Roles>();
        }
    
        public int usu_id { get; set; }
        public string usu_username { get; set; }
        public string usu_password { get; set; }
        public bool usu_estado { get; set; }
        public string usu_nombre { get; set; }
        public string usu_apellido { get; set; }
        public string usu_mail { get; set; }
        public string usu_tel { get; set; }
        public System.DateTime usu_fecha_nac { get; set; }
        public long usu_documento { get; set; }
        public int usu_intentos { get; set; }
        public string usu_direccion { get; set; }
        public int usu_doc_id { get; set; }
    
        public virtual Documentos Documentos { get; set; }
        public virtual ICollection<Estadias> Estadias { get; set; }
        public virtual ICollection<Estadias> Estadias1 { get; set; }
        public virtual ICollection<Hoteles_Usuarios> Hoteles_Usuarios { get; set; }
        public virtual ICollection<Reservas> Reservas { get; set; }
        public virtual ICollection<Usuarios_ReservasCancelaciones> Usuarios_ReservasCancelaciones { get; set; }
        public virtual ICollection<Usuarios_ReservasModificaciones> Usuarios_ReservasModificaciones { get; set; }
        public virtual ICollection<Roles> Roles { get; set; }
    }
}
