//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrbaHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios_ReservasCancelaciones
    {
        public int urc_id { get; set; }
        public int urc_res_id { get; set; }
        public int urc_usu_id { get; set; }
        public System.DateTime urc_fecha { get; set; }
        public string urc_motivo { get; set; }
    
        public virtual Reservas Reservas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
